trigger:
- main

pool:
  name: 'Default'  # or the name of your self-hosted agent pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python snakegame.py
  displayName: 'Install dependencies and run the game'
