trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python snakegame.py